name: Publish to Docker registry

on:
  push:
    paths-ignore:
      - README.md

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to dockerhub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build :tag
        if: success()
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/echo-server:${{ github.sha }} .

      - name: Push to docker hub :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKERHUB_USERNAME }}/echo-server:${{ github.sha }}

      - name: Retag
        if: success()
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/echo-server:${{ github.sha }} docker.pkg.github.com/${{ github.repository }}/echo-server:latest

      - name: Push to docker hub with latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKERHUB_USERNAME }}/echo-server:latest
